kind: pipeline
name: default

steps:
  - name: test
    image: golang
    commands:
      - go get -d -v -t ./...
      - go test -v ./...
 
  - name: lint
    image: golang
    environment:
      REVIEWDOG_GITHUB_API_TOKEN:
        from_secret: github_token
    commands:
      - go get github.com/golangci/golangci-lint/cmd/golangci-lint
      - go get github.com/reviewdog/reviewdog/cmd/reviewdog
      - go get github.com/gostaticanalysis/unused/cmd/unused
      - go install golang.org/x/tools/go/analysis/passes/shadow/cmd/shadow
      - |
        go vet -vettool=$(which shadow) . 2>&1 | reviewdog -f=govet -diff="git diff" 
      - |
        golangci-lint run --fast | reviewdog -f=golangci-lint -diff="git diff"
      - |
        go vet -vettool=$(which unused) pkgname | reviewdog -efm="%f:%l:%c: %m" -diff="git diff" 
    when:
      event:
       - push
       - tag
       - pull_request


# kind: pipeline
# name: default

# steps:
# - name: test
#   image: golang
#   commands:
#   - go test -v ./...
#   - go build
