// Code generated by MockGen. DO NOT EDIT.
// Source: dbs/redis.go

// Package mocks is a generated GoMock package.
package mocks

import (
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockDispatchRepository is a mock of DispatchRepository interface
type MockDispatchRepository struct {
	ctrl     *gomock.Controller
	recorder *MockDispatchRepositoryMockRecorder
}

// MockDispatchRepositoryMockRecorder is the mock recorder for MockDispatchRepository
type MockDispatchRepositoryMockRecorder struct {
	mock *MockDispatchRepository
}

// NewMockDispatchRepository creates a new mock instance
func NewMockDispatchRepository(ctrl *gomock.Controller) *MockDispatchRepository {
	mock := &MockDispatchRepository{ctrl: ctrl}
	mock.recorder = &MockDispatchRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockDispatchRepository) EXPECT() *MockDispatchRepositoryMockRecorder {
	return m.recorder
}

// Ping mocks base method
func (m *MockDispatchRepository) Ping() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping")
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping
func (mr *MockDispatchRepositoryMockRecorder) Ping() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockDispatchRepository)(nil).Ping))
}

// QueueSet mocks base method
func (m *MockDispatchRepository) QueueSet(queue, json string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueueSet", queue, json)
	ret0, _ := ret[0].(error)
	return ret0
}

// QueueSet indicates an expected call of QueueSet
func (mr *MockDispatchRepositoryMockRecorder) QueueSet(queue, json interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueueSet", reflect.TypeOf((*MockDispatchRepository)(nil).QueueSet), queue, json)
}

// QueueGet mocks base method
func (m *MockDispatchRepository) QueueGet(queue string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueueGet", queue)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QueueGet indicates an expected call of QueueGet
func (mr *MockDispatchRepositoryMockRecorder) QueueGet(queue interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueueGet", reflect.TypeOf((*MockDispatchRepository)(nil).QueueGet), queue)
}

// QueueRangeList mocks base method
func (m *MockDispatchRepository) QueueRangeList(queue string, start, end int64) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueueRangeList", queue, start, end)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QueueRangeList indicates an expected call of QueueRangeList
func (mr *MockDispatchRepositoryMockRecorder) QueueRangeList(queue, start, end interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueueRangeList", reflect.TypeOf((*MockDispatchRepository)(nil).QueueRangeList), queue, start, end)
}

// QueueTrim mocks base method
func (m *MockDispatchRepository) QueueTrim(queue string, start, end int64) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueueTrim", queue, start, end)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QueueTrim indicates an expected call of QueueTrim
func (mr *MockDispatchRepositoryMockRecorder) QueueTrim(queue, start, end interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueueTrim", reflect.TypeOf((*MockDispatchRepository)(nil).QueueTrim), queue, start, end)
}

// QueueGetList mocks base method
func (m *MockDispatchRepository) QueueGetList(queue string, amount int) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueueGetList", queue, amount)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QueueGetList indicates an expected call of QueueGetList
func (mr *MockDispatchRepositoryMockRecorder) QueueGetList(queue, amount interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueueGetList", reflect.TypeOf((*MockDispatchRepository)(nil).QueueGetList), queue, amount)
}

// QueueSize mocks base method
func (m *MockDispatchRepository) QueueSize(queue string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueueSize", queue)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QueueSize indicates an expected call of QueueSize
func (mr *MockDispatchRepositoryMockRecorder) QueueSize(queue interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueueSize", reflect.TypeOf((*MockDispatchRepository)(nil).QueueSize), queue)
}

// Incr mocks base method
func (m *MockDispatchRepository) Incr(key string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Incr", key)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Incr indicates an expected call of Incr
func (mr *MockDispatchRepositoryMockRecorder) Incr(key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Incr", reflect.TypeOf((*MockDispatchRepository)(nil).Incr), key)
}

// Decr mocks base method
func (m *MockDispatchRepository) Decr(key string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Decr", key)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Decr indicates an expected call of Decr
func (mr *MockDispatchRepositoryMockRecorder) Decr(key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Decr", reflect.TypeOf((*MockDispatchRepository)(nil).Decr), key)
}

// Del mocks base method
func (m *MockDispatchRepository) Del(key string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Del", key)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Del indicates an expected call of Del
func (mr *MockDispatchRepositoryMockRecorder) Del(key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Del", reflect.TypeOf((*MockDispatchRepository)(nil).Del), key)
}

// Get mocks base method
func (m *MockDispatchRepository) Get(key string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", key)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get
func (mr *MockDispatchRepositoryMockRecorder) Get(key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockDispatchRepository)(nil).Get), key)
}
